baseURL = 'https://llklkl.top/'
languageCode = 'zh-cn'
defaultContentLanguage = "zh-cn"
title = "llklkl's blog"
theme = "beautifulhugo"
forcesyncstatic = false

[params]
  description = "llklkl's blog"
  author = "llklkl"
  GitHubUser = "llklkl"

  beian = "蜀ICP备19038537号-1"

  # 主题配置
  pygmentsCodeFences = true
  pygmentsUseClasses = true
  readingTime = true
  wordCount = true
  showRelatedPosts = true

[taxonomies]
#  tag = "tags"
  category = "categories"

[Author]
  name = "llklkl"
  email = "fengl6638@gmail.com"
  github = "llklkl"

[[menu.main]]
    name = "博客"
    url = ""
    weight = 1

[[menu.main]]
    name = "目录"
    url = "categories/"
    weight = 2

[[menu.main]]
    name = "关于"
    url = "about/"
    weight = 3